# Simulation settings
NUM_STEPS = 3000
INITIAL_PRICE = 100
WARMUP_STEPS = 50

# Agents settings
NUM_NOISE_TRADERS = 5
NUM_MARKET_MAKERS = 6
NUM_INFORMED_TRADERS = 6
NUM_FUNDAMENTAL_TRADERS = 7

NUM_TREND_TRADERS = 5
TREND_TRADER_LOOKBACK = 50
TREND_TRADER_THRESHOLD = 0.2
TREND_TRADER_AGGRESSIVENESS = 3.0
TREND_TRADER_MAX_QTY = 5

NOISE_TRADER_NOISE_LEVEL = 0.05
NOISE_ORDER_PROB = 0.3
INFORMED_TRADER_SENSITIVITY = 0.2
INFORMED_TRADER_AGGRESSIVENESS = 0.2
FUNDAMENTAL_TRADER_AGGRESSIVENESS = 0.2
FUNDAMENTAL_TRADER_PRICE_ALPHA = 0.5
FUNDAMENTAL_TRADER_MAX_QTY = 5
INFORMED_TRADER_MAX_QTY = 5
FUNDAMENTAL_TRADER_ORDER_PROB = 0.7

# GBM

FUNDAMENTAL_MU = 0.0
FUNDAMENTAL_VOL = 0.20
STEPS_PER_YEAR = 12000


SEED = None

MM_BASE_SPREAD = 0.30
MM_INV_RISK = 1.0
MM_MAX_INVENTORY = 30
MM_BASE_SIZE = 3
MM_VOL_SENS = 1.5
MM_REQUOTE_THRESHOLD = 0.025
MM_MAX_QUOTE_AGE = 50
MM_TIME_HORIZON = 200
MM_ORDER_INTENSITY_K = 1.5
OPT_MM_REQUOTE_THRESHOLD = 0.05
OPT_MM_MAX_QUOTE_AGE = 50
PASSIVE_OFFSET = 0.01

# lifetime
ORDER_TTL = 500
MAX_HEDGE_SLIPPAGE = 0.5

NOISE_LEVEL_MIN = 0.02
NOISE_LEVEL_MAX = 0.04
NOISE_MAX_INVENTORY = 20
NOISE_MARKET_PROB = 0.85

INFORMED_SENSITIVITY_MIN = 0.10
INFORMED_SENSITIVITY_MAX = 0.30
INFORMED_SIGNAL_NOISE_MIN = 0.05
INFORMED_SIGNAL_NOISE_MAX = 0.20
INFORMED_TRADE_THRESHOLD = 0.10
INFORMED_MAX_INVENTORY = 30

FUNDAMENTAL_F_NOISE_SIGMA = 0.5

TREND_LOOKBACK_MIN = 20
TREND_LOOKBACK_MAX = 100

MM_RISK_AVERSION_MIN = 0.5
MM_RISK_AVERSION_MAX = 2.0
MM_VOL_SENS_MIN = 1.0
MM_VOL_SENS_MAX = 2.0

# AR
NEWS_PERSISTENCE = 0.85
NEWS_SHOCK_PROBABILITY = 0.05
NEWS_SHOCK_SIGMA = 0.1
NEWS_IMPACT_ON_F = 0.1


NUM_OPTION_MARKET_MAKERS = 4
NUM_OPTION_NOISE_TRADERS = 3
NUM_OPTION_ARB = 2
OPTION_STRIKES = [90, 100, 110]
OPTION_TAU = 30/252.0
OPTION_R = 0.00
OPTION_Q = 0.0
OPTION_VOL = 0.2
OPTION_SPREAD_FACTOR = 0.02
OPTION_ARB_THRESHOLD = 0.01
OPTION_ARB_ESTIMATED_COSTS = 1.5
MIN_OPTION_PRICE = 0.1
DELTA_HEDGE_THRESHOLD = 0.1
DELTA_HEDGE_INTERVAL = 20